import Link from "next/link";
import { notFound } from "next/navigation";
import { catalog, lifecycle } from "@/lib/product/catalog";

export default async function DesignPage({ params }: { params: Promise<{ designId: string }> }) {
  const { designId } = await params; const item = catalog.find(candidate => candidate.id === Number(designId)); if (!item) notFound();
  const action = item.status === "Live auction" ? { href: "/auctions/1", label: "Enter live auction" } : item.status === "Community vote" ? { href: "/community", label: "Support this concept" } : item.id === 1 ? { href: "/marketplace/1", label: "View authorised resale" } : { href: "/explore", label: "Follow this asset" };
  return <main className="product-main"><header className="design-hero"><div className={`design-art palette-${item.palette}`}><span>DESIGN #{item.id}</span><div className="hero-mark"><i/><b/></div><small>{item.edition.toUpperCase()} · {item.game.toUpperCase()}</small></div><div><div className="card-status"><span className="live-dot"/>{item.status}<small>{item.source === "onchain-demo" ? "Executed demo asset" : "Product preview"}</small></div><h1>{item.name}</h1><p>{item.description}</p><div className="design-actions"><Link className="button-link" href={action.href}>{action.label}</Link><Link className="text-link" href="/evidence">Inspect public proof ↗</Link></div><dl className="design-facts"><div><dt>Creator</dt><dd>{item.artist}</dd></div><div><dt>Class</dt><dd>{item.category}</dd></div><div><dt>Edition</dt><dd>{item.edition}</dd></div><div><dt>Community</dt><dd>{item.votes ? `${item.votes} signals` : "Awaiting review"}</dd></div></dl><div className="asset-disclosure">{item.source === "onchain-demo" ? "This asset represents the locally executed end-to-end demo journey. Public Sepolia currently contains deployment and configuration evidence." : "This season card is product-preview content and is not represented as a deployed on-chain asset."}</div></div></header><section className="detail-grid"><article className="panel"><p className="panel-kicker">LIFECYCLE</p><h2>Accountable from concept to collection</h2><ol className="gate-list">{lifecycle.map((stage,index) => <li key={stage}><span>{index < (item.id === 1 ? 7 : item.status === "Production" ? 5 : item.status === "Community vote" ? 3 : 2) ? "✓" : "·"}</span>{stage}<small>{index < (item.id === 1 ? 7 : 3) ? "Complete" : "Pending"}</small></li>)}</ol></article><article className="panel"><p className="panel-kicker">PLAYER RIGHTS</p><h2>Collect access, not someone else&apos;s IP</h2><p>Ownership represents a limited right to use the selected skin in the supported game under publisher terms. It does not transfer copyright, character ownership or the right to use it in every game.</p><Link className="text-link" href="/trust">Understand ownership and privacy ↗</Link></article></section><section className="evidence-preview"><div><p className="eyebrow">ONE AUDIT TRAIL</p><h2>See the decisions behind the asset.</h2><p>Public receipts show accountable transitions while sensitive source files, reports and player IDs remain private.</p></div><Link className="button-link" href="/evidence">Open evidence explorer</Link></section></main>;
}
