"use client";

import { FormEvent, useEffect, useState } from "react";
import { useAccount, useSignMessage } from "wagmi";

type ApiState = { status: "idle" | "loading" | "success" | "error"; message?: string; data?: Record<string, unknown> };
const idle: ApiState = { status: "idle" };

async function api<T extends Record<string, unknown>>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, init); const body = await response.json();
  if (!response.ok) throw new Error(body.message ?? `Request failed (${response.status})`);
  return body as T;
}

function Feedback({ state }: { state: ApiState }) {
  if (state.status === "idle") return null;
  return <div className={`api-feedback ${state.status}`}><span>{state.status === "loading" ? "Working" : state.status === "success" ? "Backend confirmed" : "Action needs attention"}</span><p>{state.message}</p>{state.data && <details><summary>View returned record</summary><pre>{JSON.stringify(state.data, null, 2)}</pre></details>}</div>;
}

export function UploadWorkspace() {
  const { address } = useAccount();
  const { signMessageAsync } = useSignMessage();
  const [state, setState] = useState<ApiState>(idle); const [fileId, setFileId] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!address) return; setState({ status: "loading", message: "Uploading and hashing the private evidence package…" }); const source = new FormData(event.currentTarget); const upload = new FormData(); upload.set("designId", String(Date.now())); upload.set("category", "concept-art"); upload.set("file", source.get("file")!); try { const data = await api<Record<string, unknown>>("/api/files/upload", { method: "POST", body: upload }); const authorizationTimestamp=Math.floor(Date.now()/1000); const creatorWallet=address.toLowerCase(); const message=`MOBA Forge submission\nCreator: ${creatorWallet}\nArtwork SHA-256: ${String(data.sha256).toLowerCase()}\nTimestamp: ${authorizationTimestamp}`; setState({ status: "loading", message: "Confirm the wallet signature that assigns this private draft to you…" }); const authorizationSignature=await signMessageAsync({ message }); const draft = await api<Record<string, unknown>>("/api/designs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ creatorWallet, authorizationTimestamp, authorizationSignature, name: source.get("name"), description: source.get("description"), game: source.get("game"), category: source.get("role"), edition: source.get("edition"), aiDisclosure: source.get("aiDisclosure"), provenance: source.get("provenance"), fileId: data.fileId, fileName: data.fileName, storageURI: data.storageURI, artworkHash: data.sha256 }) }); setFileId(String(data.fileId)); window.dispatchEvent(new CustomEvent("moba:evidence-uploaded", { detail: { storageURI: String(data.storageURI), sha256: String(data.sha256), disclosure: String(source.get("aiDisclosure")), provenance: String(source.get("provenance")) } })); window.dispatchEvent(new CustomEvent("moba:lifecycle-updated")); setState({ status: "success", message: "Wallet-owned private draft stored. Its URI and evidence hashes are loaded into Submit design below; signing that transaction creates the public design ID.", data: { ...data, localId: draft.localId } }); } catch (error) { setState({ status: "error", message: error instanceof Error ? error.message : "Upload failed" }); } }
  return <section className="backend-panel" id="submission"><div className="backend-intro"><span>PRIVATE STORAGE → PUBLIC HASH</span><h2>Create a design submission</h2><p>The original file stays in controlled storage. Only its URI and integrity references enter the public contract lifecycle.</p></div><form className="backend-form" onSubmit={submit}><label>Design name<input name="name" placeholder="e.g. Verdant Sentinel" maxLength={80} required /></label><label>Target game<input name="game" defaultValue="Demo MOBA" maxLength={80} required /></label><label>Hero role<select name="role" defaultValue="Mage"><option>Tank</option><option>Assassin</option><option>Mage</option><option>Marksman</option><option>Support</option></select></label><label>Edition<input name="edition" defaultValue="Concept" maxLength={40} /></label><label className="wide">Public description<textarea name="description" placeholder="Explain the visual concept and intended player experience" maxLength={600} required /></label><label>AI disclosure reference<input name="aiDisclosure" placeholder="AI tools used, or no-AI declaration" required /></label><label>Provenance reference<input name="provenance" placeholder="Sketch/source ownership evidence" required /></label><label className="wide">Choose PNG, JPG, JPEG, WebP, PDF, JSON, GLB, GLTF, FBX, BLEND or OBJ (max 50 MiB)<input name="file" type="file" accept=".png,.jpg,.jpeg,.webp,.pdf,.json,.glb,.gltf,.fbx,.blend,.obj" required /></label><button disabled={!address || state.status === "loading"}>{!address ? "Connect an Artist wallet" : state.status === "loading" ? "Preparing submission…" : "Save private draft and hash"}</button>{fileId && <code className="copy-value">{fileId}</code>}</form><Feedback state={state} /></section>;
}

export function VerificationWorkspace() {
  const { address } = useAccount(); const [state, setState] = useState<ApiState>(idle); const [report, setReport] = useState<Record<string, unknown> | null>(null);
  async function prescreen(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setState({ status: "loading", message: "Running evidence completeness checks…" }); try { const data = await api<Record<string, unknown>>("/api/verification/pre-screen", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ designId: Number(form.get("designId")), aiUsed: form.get("aiUsed") === "yes", disclosureComplete: form.get("disclosureComplete") === "yes", evidenceFileIds: String(form.get("evidenceFileIds") || "").split(",").map(v => v.trim()).filter(Boolean) }) }); setReport(data); setState({ status: "success", message: `Pre-screen complete: ${data.overallRisk} risk. Human decision is still required.`, data }); } catch (error) { setState({ status: "error", message: error instanceof Error ? error.message : "Pre-screen failed" }); } }
  async function decide(decision: string) { if (!report || !address) return; setState({ status: "loading", message: "Persisting the accountable human review…" }); const { reportId: _id, ...automatedSummary } = report; try { const data = await api<Record<string, unknown>>("/api/verification/reports", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ designId: Number(report.designId), automatedSummary, decision, verifierAddress: address, notes: "Reviewed in MOBA Forge verification desk" }) }); setState({ status: "success", message: "Human report persisted. Anchor its reportHash with the matching on-chain action below.", data }); } catch (error) { setState({ status: "error", message: error instanceof Error ? error.message : "Review failed" }); } }
  return <section className="backend-panel"><div className="backend-intro"><span>BACKEND RISK ASSISTANCE</span><h2>Evidence pre-screen</h2><p>Automated checks organize evidence; a connected verifier makes the human decision and then anchors the report hash on-chain.</p></div><form className="backend-form" onSubmit={prescreen}><label>Design ID<input name="designId" type="number" min="1" defaultValue="1" /></label><label>AI used?<select name="aiUsed" defaultValue="yes"><option value="yes">Yes, disclosed</option><option value="no">No</option></select></label><label>Disclosure complete?<select name="disclosureComplete" defaultValue="yes"><option value="yes">Complete</option><option value="no">Incomplete</option></select></label><label>Evidence file IDs<input name="evidenceFileIds" placeholder="concept-art-1-…, ai-disclosure-1-…" /></label><button>Run pre-screen</button></form>{report && <div className="decision-row"><button disabled={!address} onClick={() => decide("APPROVED")}>Approve report</button><button className="ghost" disabled={!address} onClick={() => decide("REVISION_REQUIRED")}>Request revision</button></div>}<Feedback state={state} /></section>;
}

export function ProductionWorkspace() {
  const { address } = useAccount(); const [state, setState] = useState<ApiState>(idle); const [record, setRecord] = useState<Record<string, unknown> | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setState({ status: "loading", message: "Versioning the production package…" }); try { const data = await api<Record<string, unknown>>("/api/production/records", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ designId: Number(form.get("designId")), productionStudio: form.get("studio"), modelFileURI: form.get("modelFileURI"), approvedGame: form.get("game") }) }); setRecord(data); setState({ status: "success", message: `Production ${data.version} created with deterministic hashes.`, data }); } catch (error) { setState({ status: "error", message: error instanceof Error ? error.message : "Production submission failed" }); } }
  async function review(qaStatus: string) { if (!record || !address) return; setState({ status: "loading", message: "Saving technical review…" }); try { const data = await api<Record<string, unknown>>("/api/production/review", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ designId: record.designId, version: record.version, qaStatus, reviewerAddress: address, notes: "Reviewed in production workspace" }) }); setState({ status: "success", message: "Technical review saved. Complete the corresponding wallet action below.", data }); } catch (error) { setState({ status: "error", message: error instanceof Error ? error.message : "Review failed" }); } }
  return <section className="backend-panel"><div className="backend-intro"><span>VERSIONED PRODUCTION</span><h2>Build and compatibility package</h2><p>Model files stay private while production and compatibility hashes connect the studio record to the contract approval.</p></div><form className="backend-form" onSubmit={submit}><label>Design ID<input name="designId" type="number" min="1" defaultValue="1" /></label><label>Production studio<input name="studio" defaultValue="MOBA Forge Lab" /></label><label>Model file URI<input name="modelFileURI" defaultValue="ipfs://production-package-v1" /></label><label>Target game<input name="game" defaultValue="Demo MOBA" /></label><button>Create next version</button></form>{record && <div className="decision-row"><button disabled={!address} onClick={() => review("APPROVED")}>Approve QA</button><button className="ghost" disabled={!address} onClick={() => review("REWORK_REQUIRED")}>Require rework</button></div>}<Feedback state={state} /></section>;
}

export function PlayerDeliveryWorkspace() {
  const { address } = useAccount(); const [gameId, setGameId] = useState(""); const [state, setState] = useState<ApiState>(idle); const [link, setLink] = useState<Record<string, unknown> | null>(null);
  useEffect(() => { if (!address) { setLink(null); return; } api<Record<string, unknown>>(`/api/accounts/${address}`).then(setLink).catch(() => setLink(null)); }, [address]);
  async function connectGame(event: FormEvent) { event.preventDefault(); if (!address) return; setState({ status: "loading", message: "Linking the private game account…" }); try { const data = await api<Record<string, unknown>>("/api/accounts/link", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ walletAddress: address, gameAccountId: gameId }) }); setLink(data); setState({ status: "success", message: "Game account linked. It remains off-chain and private.", data }); } catch (error) { setState({ status: "error", message: error instanceof Error ? error.message : "Account link failed" }); } }
  async function checkDelivery() { if (!address) return; setState({ status: "loading", message: "Checking delivery state…" }); try { const data = await api<Record<string, unknown>>(`/api/game/status/${address}/1`); setState({ status: "success", message: `Delivery state: ${data.status}`, data }); } catch (error) { setState({ status: "error", message: error instanceof Error ? error.message : "No delivery record yet" }); } }
  return <section className="backend-panel player-delivery"><div className="backend-intro"><span>PLAYER DELIVERY</span><h2>Connect your game account</h2><p>Your wallet proves entitlement ownership. Your private player identifier tells the game service where to deliver access.</p></div>{link ? <div className="linked-account"><span>LINKED</span><strong>{String(link.gameAccountId)}</strong><small>{String(link.walletAddress)}</small><button className="ghost" onClick={checkDelivery}>Check skin delivery</button></div> : <form className="backend-form" onSubmit={connectGame}><label className="wide">Game account ID<input value={gameId} onChange={(event) => setGameId(event.target.value)} placeholder="your-player-id" minLength={3} required /></label><button disabled={!address}>{address ? "Connect game account" : "Connect wallet first"}</button></form>}<Feedback state={state} /></section>;
}

export function SystemStatusWorkspace() {
  const [indexer, setIndexer] = useState<Record<string, unknown> | null>(null); const [evidence, setEvidence] = useState<Record<string, unknown> | null>(null);
  const [designs, setDesigns] = useState<Array<{ stage: string; public: boolean }>>([]);
  async function refresh() { const [indexerData, evidenceData, designData] = await Promise.all([api<Record<string, unknown>>("/api/indexer/status"), api<Record<string, unknown>>("/api/evidence"), api<{ designs: Array<{ stage: string; public: boolean }> }>("/api/designs")]); setIndexer(indexerData); setEvidence(evidenceData); setDesigns(designData.designs); }
  useEffect(() => { refresh().catch(() => undefined); }, []);
  const evidenceRows = evidence?.evidence as unknown[] | undefined;
  return <section className="backend-panel system-panel"><div className="backend-intro"><span>LIVE PRODUCT HEALTH</span><h2>Data and evidence pipeline</h2><p>Operational state is read from the same APIs used by the public evidence experience.</p></div><div className="health-grid admin-health"><div><span className="health-light"/><small>Indexer storage</small><strong>{String(indexer?.storage ?? "Loading…")}</strong><p>Cursor {String(indexer?.cursor ?? "—")}</p></div><div><span className="health-light"/><small>Public evidence</small><strong>{String(evidence?.source ?? "Loading…")}</strong><p>{evidenceRows?.length ?? 0} decoded events</p></div><div><span className="health-light"/><small>Settlement chain</small><strong>Sepolia 11155111</strong><p>Seven contracts configured</p></div><div><small>Private drafts</small><strong>{designs.filter(item => item.stage === "DRAFT").length}</strong><p>Awaiting artist signature</p></div><div><small>Review pipeline</small><strong>{designs.filter(item => !item.public && item.stage !== "DRAFT").length}</strong><p>Submitted through technical QA</p></div><div><small>Public catalog</small><strong>{designs.filter(item => item.public).length}</strong><p>Passed every market gate</p></div></div><button className="ghost" onClick={() => refresh()}>Refresh service health</button></section>;
}
