import { keccak256, parseUnits, stringToBytes, type Abi } from "viem";

import { assetRegistryAbi, compatibilityAbi, entitlementAbi, paymentAbi, primaryAbi, secondaryAbi, votingAbi } from "@/lib/blockchain/abis";
import type { ContractKey } from "@/config/contracts";

export type ProductActionId =
  | "submit-design" | "request-revision" | "verify-design" | "publisher-eligibility" | "record-agreement"
  | "open-voting" | "vote" | "finalize-voting" | "submit-production" | "approve-compatibility" | "require-rework"
  | "create-auction" | "approve-primary" | "place-bid" | "withdraw-refund" | "settle-auction" | "withdraw-primary"
  | "set-transferable" | "list-resale" | "approve-resale" | "buy-resale" | "cancel-listing" | "withdraw-resale"
  | "suspend-design" | "reinstate-design" | "pause-entitlement" | "unpause-entitlement";

export type ActionInput = { key: string; label: string; defaultValue: string; type?: "text" | "number" | "datetime-local" };
export type ProductAction = {
  id: ProductActionId; title: string; description: string; contract: ContractKey; abi: Abi; functionName: string;
  inputs: ActionInput[]; buildArgs: (values: Record<string, string>, chainId: number) => readonly unknown[];
};

const hash = (value: string) => keccak256(stringToBytes(value));
const evidenceHash = (value: string) => /^0x[0-9a-f]{64}$/i.test(value) ? value as `0x${string}` : hash(value);
const integer = (value: string) => BigInt(value || "0");
const token = (value: string) => parseUnits(value || "0", 18);
const time = (value: string) => BigInt(Math.floor(new Date(value).getTime() / 1000));
const future = (minutes: number) => new Date(Date.now() + minutes * 60_000).toISOString().slice(0, 16);
const field = (key: string, label: string, defaultValue: string, type: ActionInput["type"] = "text"): ActionInput => ({ key, label, defaultValue, type });

export const productActions: Record<ProductActionId, ProductAction> = {
  "submit-design": { id: "submit-design", title: "Submit design on-chain", description: "Anchor the metadata URI and integrity hashes from the uploaded evidence.", contract: "assetRegistry", abi: assetRegistryAbi, functionName: "submitDesign", inputs: [field("uri", "Metadata URI", "ipfs://verdant-sentinel"), field("artwork", "Artwork evidence", "verdant-sentinel-artwork"), field("disclosure", "AI disclosure", "ai-disclosure-v1"), field("provenance", "Provenance evidence", "creator-evidence-v1")], buildArgs: (v) => [v.uri, evidenceHash(v.artwork), evidenceHash(v.disclosure), evidenceHash(v.provenance)] },
  "request-revision": { id: "request-revision", title: "Request revision", description: "Record a public reason hash while detailed review notes stay private.", contract: "assetRegistry", abi: assetRegistryAbi, functionName: "requestRevision", inputs: [field("designId", "Design ID", "1", "number"), field("reason", "Reason reference", "revision-required-v1")], buildArgs: (v) => [integer(v.designId), hash(v.reason)] },
  "verify-design": { id: "verify-design", title: "Approve verification", description: "Anchor the persisted human report hash.", contract: "assetRegistry", abi: assetRegistryAbi, functionName: "verifyDesign", inputs: [field("designId", "Design ID", "1", "number"), field("report", "Report reference", "verification-report-v1")], buildArgs: (v) => [integer(v.designId), hash(v.report)] },
  "publisher-eligibility": { id: "publisher-eligibility", title: "Approve concept eligibility", description: "Record the publisher review hash and unlock voting eligibility.", contract: "assetRegistry", abi: assetRegistryAbi, functionName: "approveConceptEligibility", inputs: [field("designId", "Design ID", "1", "number"), field("review", "Review reference", "publisher-review-v1")], buildArgs: (v) => [integer(v.designId), hash(v.review)] },
  "record-agreement": { id: "record-agreement", title: "Record commercial agreement", description: "Anchor the agreement and artist revenue terms without publishing the legal document.", contract: "assetRegistry", abi: assetRegistryAbi, functionName: "recordAgreement", inputs: [field("designId", "Design ID", "1", "number"), field("agreement", "Agreement reference", "agreement-v1"), field("primaryBps", "Artist primary BPS", "8000", "number"), field("resaleBps", "Artist resale BPS", "500", "number")], buildArgs: (v) => [integer(v.designId), hash(v.agreement), Number(v.primaryBps), Number(v.resaleBps)] },
  "open-voting": { id: "open-voting", title: "Open voting round", description: "Open a real time-boxed round for eligible candidates.", contract: "voting", abi: votingAbi, functionName: "openVoting", inputs: [field("roundId", "Round ID", "1", "number"), field("designIds", "Candidate design IDs", "1"), field("start", "Start", future(1), "datetime-local"), field("end", "End", future(6), "datetime-local")], buildArgs: (v) => [integer(v.roundId), v.designIds.split(",").map((x) => integer(x.trim())), time(v.start), time(v.end)] },
  vote: { id: "vote", title: "Vote for design", description: "Sign one vote from the connected fan wallet.", contract: "voting", abi: votingAbi, functionName: "vote", inputs: [field("roundId", "Round ID", "1", "number"), field("designId", "Design ID", "1", "number")], buildArgs: (v) => [integer(v.roundId), integer(v.designId)] },
  "finalize-voting": { id: "finalize-voting", title: "Finalize voting", description: "Finalize after the public deadline and record the winner.", contract: "voting", abi: votingAbi, functionName: "finalizeVoting", inputs: [field("roundId", "Round ID", "1", "number")], buildArgs: (v) => [integer(v.roundId)] },
  "submit-production": { id: "submit-production", title: "Submit production hash", description: "Anchor the current production package and compatibility-report hashes.", contract: "compatibility", abi: compatibilityAbi, functionName: "submitProduction", inputs: [field("designId", "Design ID", "1", "number"), field("production", "Production reference", "production-package-v1"), field("compatibility", "Compatibility reference", "compatibility-report-v1"), field("version", "Version", "v1")], buildArgs: (v) => [integer(v.designId), hash(v.production), hash(v.compatibility), v.version] },
  "approve-compatibility": { id: "approve-compatibility", title: "Approve compatibility", description: "Record the supported-game hash and maximum supply after reviewing the pending production package.", contract: "compatibility", abi: compatibilityAbi, functionName: "approveCompatibility", inputs: [field("designId", "Design ID", "1", "number"), field("game", "Approved game", "Demo MOBA"), field("maxSupply", "Maximum supply", "1", "number")], buildArgs: (v) => [integer(v.designId), hash(v.game), integer(v.maxSupply)] },
  "require-rework": { id: "require-rework", title: "Require rework", description: "Return the production package for correction with a public reason hash.", contract: "compatibility", abi: compatibilityAbi, functionName: "requireRework", inputs: [field("designId", "Design ID", "1", "number"), field("reason", "Reason reference", "qa-rework-v1")], buildArgs: (v) => [integer(v.designId), hash(v.reason)] },
  "create-auction": { id: "create-auction", title: "Create primary auction", description: "The contract independently checks all market-ready gates.", contract: "primary", abi: primaryAbi, functionName: "createAuction", inputs: [field("designId", "Design ID", "1", "number"), field("reserve", "Reserve MockVND", "100", "number"), field("increment", "Minimum increment", "10", "number"), field("start", "Start", future(1), "datetime-local"), field("end", "End", future(8), "datetime-local")], buildArgs: (v) => [integer(v.designId), token(v.reserve), token(v.increment), time(v.start), time(v.end)] },
  "approve-primary": { id: "approve-primary", title: "Approve auction spending", description: "Allow the primary contract to transfer the selected MockVND amount.", contract: "payment", abi: paymentAbi, functionName: "approve", inputs: [field("amount", "Amount MockVND", "150", "number")], buildArgs: (v, _chainId) => ["PRIMARY_ADDRESS", token(v.amount)] },
  "place-bid": { id: "place-bid", title: "Place bid", description: "Move MockVND into contract escrow and become the leading bidder.", contract: "primary", abi: primaryAbi, functionName: "placeBid", inputs: [field("auctionId", "Auction ID", "1", "number"), field("amount", "Amount MockVND", "150", "number")], buildArgs: (v) => [integer(v.auctionId), token(v.amount)] },
  "withdraw-refund": { id: "withdraw-refund", title: "Withdraw refund", description: "Claim the connected bidder's pull-payment refund.", contract: "primary", abi: primaryAbi, functionName: "withdrawRefund", inputs: [field("auctionId", "Auction ID", "1", "number")], buildArgs: (v) => [integer(v.auctionId)] },
  "settle-auction": { id: "settle-auction", title: "Settle auction", description: "Finalize payment allocation and mint the entitlement after deadline.", contract: "primary", abi: primaryAbi, functionName: "settle", inputs: [field("auctionId", "Auction ID", "1", "number")], buildArgs: (v) => [integer(v.auctionId)] },
  "withdraw-primary": { id: "withdraw-primary", title: "Withdraw primary proceeds", description: "Claim the connected recipient's primary-market receivable.", contract: "primary", abi: primaryAbi, functionName: "withdrawProceeds", inputs: [], buildArgs: () => [] },
  "set-transferable": { id: "set-transferable", title: "Enable authorised resale", description: "Allow this entitlement to move only through the authorised marketplace.", contract: "entitlement", abi: entitlementAbi, functionName: "setTransferable", inputs: [field("tokenId", "Token ID", "1", "number")], buildArgs: (v) => [integer(v.tokenId), true] },
  "list-resale": { id: "list-resale", title: "List entitlement", description: "Create an authorised listing while ownership remains with the seller.", contract: "secondary", abi: secondaryAbi, functionName: "listForResale", inputs: [field("designId", "Design ID", "1", "number"), field("tokenId", "Token ID", "1", "number"), field("price", "Price MockVND", "200", "number")], buildArgs: (v) => [integer(v.designId), integer(v.tokenId), token(v.price)] },
  "approve-resale": { id: "approve-resale", title: "Approve resale spending", description: "Allow the secondary contract to transfer the selected MockVND amount.", contract: "payment", abi: paymentAbi, functionName: "approve", inputs: [field("amount", "Amount MockVND", "200", "number")], buildArgs: (v) => ["SECONDARY_ADDRESS", token(v.amount)] },
  "buy-resale": { id: "buy-resale", title: "Purchase entitlement", description: "Atomically pay, transfer ownership and allocate royalties.", contract: "secondary", abi: secondaryAbi, functionName: "buyResale", inputs: [field("listingId", "Listing ID", "1", "number")], buildArgs: (v) => [integer(v.listingId)] },
  "cancel-listing": { id: "cancel-listing", title: "Cancel listing", description: "Deactivate an unsold listing owned by the connected seller.", contract: "secondary", abi: secondaryAbi, functionName: "cancelListing", inputs: [field("listingId", "Listing ID", "1", "number")], buildArgs: (v) => [integer(v.listingId)] },
  "withdraw-resale": { id: "withdraw-resale", title: "Withdraw resale proceeds", description: "Claim the connected recipient's resale receivable.", contract: "secondary", abi: secondaryAbi, functionName: "withdrawProceeds", inputs: [], buildArgs: () => [] },
  "suspend-design": { id: "suspend-design", title: "Suspend design", description: "Block new market activity while retaining ownership and evidence.", contract: "assetRegistry", abi: assetRegistryAbi, functionName: "suspendDesign", inputs: [field("designId", "Design ID", "1", "number"), field("reason", "Reason reference", "risk-investigation-v1")], buildArgs: (v) => [integer(v.designId), hash(v.reason)] },
  "reinstate-design": { id: "reinstate-design", title: "Reinstate design", description: "Restore the design's pre-suspension lifecycle state.", contract: "assetRegistry", abi: assetRegistryAbi, functionName: "reinstateDesign", inputs: [field("designId", "Design ID", "1", "number")], buildArgs: (v) => [integer(v.designId)] },
  "pause-entitlement": { id: "pause-entitlement", title: "Pause entitlement transfers", description: "Emergency stop for mint and transfer paths.", contract: "entitlement", abi: entitlementAbi, functionName: "pause", inputs: [], buildArgs: () => [] },
  "unpause-entitlement": { id: "unpause-entitlement", title: "Unpause entitlement transfers", description: "Restore normal entitlement operations after review.", contract: "entitlement", abi: entitlementAbi, functionName: "unpause", inputs: [], buildArgs: () => [] },
};
